version: '3'

services:

  flask:
    image: flask_image
    build:
      context: .
    container_name: flask_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - appdata:/flask-app
    command: cat /flask-app/app/database/dao.py
    networks:
      - mongo-network
    depends_on:
      - mongo-db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - .env-mongo
    links:
      - mongo-db
    networks:
      - mongo-network
    restart: always
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo-network


networks:
    mongo-network:
      driver: bridge

volumes:
  mongodb_data_container:
    driver: local
  appdata:
    driver: local